version: "2"

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

formatters:
  enable:
    - gofumpt
    - gci
  settings:
    gofumpt:
      extra-rules: true
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/mgorozii/perftester)

linters:
  default: standard
  enable:
    - errcheck
    - gosec
    - gocritic
    - misspell
    - bodyclose
    - noctx
    - prealloc
    - tparallel
    - perfsprint
    - sloglint
    - modernize
    - usestdlibvars
    - tagalign

linters-settings:
  govet:
    enable:
      - shadow
  sloglint:
    no-global: "all"
    context: "all"
    static-msg: true
    no-mixed-args: true
    key-naming-case: "snake"

issues:
  max-same-issues: 0
  exclude-use-default: false
