apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadtestd
spec:
  replicas: 1
  selector:
    matchLabels: {app: loadtestd}
  template:
    metadata:
      labels: {app: loadtestd}
    spec:
      serviceAccountName: loadtestd
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
        - name: postgres
          image: "{{ .Values.postgres.image }}"
