apiVersion: v1
kind: ServiceAccount
metadata:
  name: loadtestd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: loadtestd
rules:
  - apiGroups: [""]
    resources: ["namespaces","pods","services","configmaps"]
    verbs: ["get","list","watch","create","delete"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get","list","watch","create","delete"]
  - apiGroups: ["serving.kserve.io"]
    resources: ["servingruntimes","clusterservingruntimes","inferenceservices"]
    verbs: ["get","list","watch","create","delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: loadtestd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: loadtestd
subjects:
  - kind: ServiceAccount
    name: loadtestd
    namespace: loadtest-system
